---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfmetrics/catalyst

inputs:
  - name: ci-task-test
  - name: dora-src

run:
  path: ci-task-test/tasks/dora/task.sh

params:
  CF_USERNAME:
  CF_PASSWORD:
  SYSTEM_DOMAIN:

