---
gcs-service-account: &gcs-service-account ((appwatch-service-account-json))

resource_types:
- name: slack-notification
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource


resources:
- name: ci-task-test
  type: git
  source:
    uri: https://github.com/hmanukyanVMw/ci-task-test.git
    branch: master
  check_every: 5m

- name: slack-alert
  type: slack-notification
  icon: slack
  source:
    url: https://hooks.slack.com/services/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

- name: ci-docker
  type: docker-image
  source:
    email: ((docker-email))
    password: ((docker-password))
    repository: pcfmetrics/catalyst
    username: ((docker-username))
    tag: ((docker-tag))

  #### Update release version ####
jobs:
- name: something-every-hour
  plan:
    - in_parallel:
        - get: ci-docker
        - get: ci-task-test
    - task: create-slack-message
      file: ci-task-test/Concurse/tasks/alert-message-create/task.yml
      params:
        TITLE: Metric Store 102.99 Deploy
        TEAM: metric-store-log-cache
  on_success:
    do:
      - put: slack-alert
        params:
          silent: true
          channel: new-test
          attachments_file: metadata/alert_message_success

- name: get-product-envs
  serial: true
  plan:
    - in_parallel:
        - get: ci-docker
        - get: ci-task-test
    - task: get-app-metrics-info
      image: ci-docker
      config:
        platform: linux
        inputs:
          - name: ci-task-test
            optional: true
        outputs:
          - name: metadata
        params:
        run:
          path: bash
          args:
            - -ce
            - |
              pushd ci-task-test
                LAST_COMMIT==$(git rev-parse HEAD)
                LAST_COMMIT_DATE=$(git log --author="$a" --pretty="%ai" | head -n1)
              popd

              echo $LAST_COMMIT
              BUILD_LINK="*<\${ATC_EXTERNAL_URL}/teams/${team}/pipelines/\${BUILD_PIPELINE_NAME}/jobs/\${BUILD_JOB_NAME}/builds/\${BUILD_NAME}|See in pipeline>*"
              TITLE="Metric Store core metrics info"

              mkdir -p metadata
              touch metadata/core_metrics
              new=$(jq -n --arg t "${TITLE}" --arg lc "${LAST_COMMIT}" --arg ad "${LAST_COMMIT_DATE}" --arg bl "${BUILD_LINK}" '[{
                      "blocks": [
                          {
                              "type": "section",
                              "text": {
                                  "type": "plain_text",
                                  "text": $t,
                                  "emoji": true
                              }
                          },
                          {
                              "type": "section",
                              "fields": [
                                  {
                                      "type": "mrkdwn",
                                      "text": "Last Commit:"
                                  },
                                  {
                                      "type": "mrkdwn",
                                      "text": $lc
                                  }
                              ]
                          },
                          {
                              "type": "section",
                              "fields": [
                                  {
                                      "type": "mrkdwn",
                                      "text": "Author Date"
                                  },
                                  {
                                      "type": "mrkdwn",
                                      "text": $ad
                                  }
                              ]
                          },
                          {
                              "type": "section",
                              "text": {
                                  "type": "mrkdwn",
                                  "text": $bl
                              }
                          }
                      ]
                  }]')
              echo $new > metadata/core_metrics
  on_success:
    do:
      - put: slack-alert
        params:
          silent: true
          channel: new-test
          attachments_file: metadata/core_metrics

#### Organize Jobs ####
groups:
  - name: slack-webhook
    jobs:
      - something-every-hour
      - get-product-envs
