---
resource_types:
- name: slack-notification
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: ci-task-test
  type: git
  source:
    uri: https://github.com/hmanukyanVMw/ci-task-test.git
    branch: master
  check_every: 5m

- name: slack-alert
  type: slack-notification
  icon: slack
  source:
    url: https://hooks.slack.com/services/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

- name: ci-docker
  type: docker-image
  source:
    email: ((docker-email))
    password: ((docker-password))
    repository: pcfmetrics/catalyst
    username: ((docker-username))
    tag: ((docker-tag))

  #### Update release version ####
jobs:
- name: something-every-hour
  plan:
    - in_parallel:
        - get: ci-docker
        - get: ci-task-test
    - task: create-slack-message
      file: ci-task-test/Concurse/tasks/alert-message-create/task.yml
      params:
        TITLE: Metric Store 102.99 Deploy
        TEAM: metric-store-log-cache
  on_success:
    do:
      - put: slack-alert
        params:
          silent: true
          channel: new-test
          attachments_file: metadata/alert_message_success


- name: get-product-envs
  serial: true
  plan:
    - in_parallel:
        - get: ci-docker
        - get: ci-task-test
    - task: get-app-metrics-info
      image: ci-docker
      file: ci-task-test/Concurse/tasks/app-metrics-version/task.yml

#### Organize Jobs ####
groups:
  - name: push dora
    jobs:
      - something-every-hour
      - get-product-envs
