---
resource_types:
- name: slack-notification
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: ci-task-test
  type: git
  source:
    uri: https://github.com/hmanukyanVMw/ci-task-test.git
    branch: master
  check_every: 5m

- name: slack-alert
  type: slack-notification
  icon: slack
  source:
    url: https://hooks.slack.com/services/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

- name: dora-src
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git
    branch: main
    private_key: ((catalyst-git-key))

- name: ci-docker
  type: docker-image
  source:
    email: ((docker-email))
    password: ((docker-password))
    repository: pcfmetrics/catalyst
    username: ((docker-username))
    tag: ((docker-tag))

  #### Update release version ####
jobs:
- name: something-every-hour
  plan:
    - in_parallel:
        - get: ci-docker
        - get: dora-src
        - get: ci-task-test
    - task: create-slack-message
        file: ci-task-test/tasks/alert-message-create/task.yml
        input_mapping: { slack-rate-limit-version: notification-cf-deploy-version }
        params:
          TITLE: Metric Store CF Deploy
          TEAM: metric-store-log-cache
  on_failure:
    do:
      - put: slack-alert
        params:
          silent: true
          channel: new-test
          attachments_file: metadata/alert_message_success
#### Organize Jobs ####
groups:
  - name: push dora
    jobs:
      - something-every-hour
