---
resource_types:
- name: slack-notification
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: slack-alert
  type: slack-notification
  icon: slack
  source:
    url: https://hooks.slack.com/services/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

- name: dora-src
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git
    branch: main
    private_key: ((catalyst-git-key))

- name: ci-docker
  type: docker-image
  source:
    email: ((docker-email))
    password: ((docker-password))
    repository: pcfmetrics/catalyst
    username: ((docker-username))
    tag: ((docker-tag))

  #### Update release version ####
jobs:
- name: something-every-hour
  plan:
    - in_parallel:
        - get: ci-docker
        - get: dora-src
    - task: push-dora-success
      image: ci-docker
      config:
        platform: linux
        params:
          CF_USERNAME: ((cf-username))
          CF_PASSWORD: ((cf-password))
          SYSTEM_DOMAIN: ((system-domain))
        run:
          path: bash
          args:
            - -ce
            - |
              cf api api.${SYSTEM_DOMAIN} --skip-ssl-validation
              cf auth ${CF_USERNAME} ${CF_PASSWORD}
              cf target -o system -s system

              pushd dora-src/assets/dora/dora
                cf push dora
              popd
        inputs:
          - name: dora-src
  on_failure:
    do:
      - put: slack-alert
        params:
          silent: true
          attachments_file: ci-task-test/metadata/alert_message_failure
#### Organize Jobs ####
groups:
  - name: push dora
    jobs:
      - something-every-hour
