platform: linux

image_resource:
  type: docker-image
  source:
    repository: logcache/base

inputs:
  - name: ci-task-test
  - name: slack-rate-limit-version
    optional: true

outputs:
  - name: metadata

run:
  path: ci-task-test/Concource/tasks/alert-message-create/task.sh

params:
  TITLE:
  TEAM: main
