---
platform: linux

inputs:
  - name: tested-product

outputs:
  - name: metadata

run:
  path: bash
  args:
    - -ceuf
    - |
      PRODUCT_FILE=$(find tested-product -name app-metrics-*.pivotal)
      PRODUCT_VERSION=$(cat tested-product/version)
      TITLE="Created tile for App Metrics $PRODUCT_VERSION"
      Authenticated_URL="https://storage.cloud.google.com/catalyst-app/main/artifacts/$PRODUCT_FILE"
      GSUITIL_URI="gs://catalyst-app/main/artifacts/$PRODUCT_FILE"

      mkdir -p metadata
      touch metadata/release-version
      echo "starting task"
      new=$(jq -n --arg t "${TITLE}" --arg aurl "${Authenticated_URL}" --arg guri "${GSUITIL_URI}" '[{
          "blocks": [
              {
                  "type": "section",
                  "text": {
                      "type": "plain_text",
                      "text": $t,
                      "emoji": true
                  }
              },
              {
                  "type": "section",
                  "fields": [
                      {
                          "type": "mrkdwn",
                          "text": "Authenticated URL:"
                      },
                      {
                          "type": "mrkdwn",
                          "text": $aurl
                      }
                  ]
              },
              {
                  "type": "section",
                  "fields": [
                      {
                          "type": "mrkdwn",
                          "text": "gsutil URI:"
                      },
                      {
                          "type": "mrkdwn",
                          "text": $guri
                      }
                  ]
              }
          ]
      }]')
      echo $new > metadata/release-version
