groups:
- name: tools
  jobs:
  - emitter

resources:
- name: loggregator-tools
  type: git
  source:
    uri: https://github.com/hmanukyanVMw/ci-task-test.git
    branch: master
    paths:
      - EmitterCI
  check_every: 5m
- name: ci-task-test
  type: git
  source:
    uri: https://github.com/hmanukyanVMw/ci-task-test.git
    branch: master
    paths:
      - EmitterCI
  check_every: 5m

- name: emitter-image-docker-build-context
  type: git
  source:
    uri: https://github.com/hmanukyanVMw/ci-task-test.git
    branch: master
    paths:
      - EmitterCI/docker-images/emitter
    check_every: 5m

- name: emitter-image
  type: docker-image
  source:
    repository: loggregator/emitter
    username: hmanukyan
    password: DocVMwdeno_!9Hms^

jobs:
- name: emitter
  plan:
  - in_parallel:
    - get: emitter-image-docker-build-context
      trigger: true
    - get: loggregator-tools
      trigger: true
    - get: ci-task-test
  - task: build-image
    file: ci-task-test/EmitterCI/build-go-docker-image/task.yml
    input_mapping:
      context-repo: emitter-image-docker-build-context
      source-repo: loggregator-tools
    params:
      CONTEXT_PATH: docker-images/emitter
      BASE_PACKAGE: github.com/hmanukyanVMw/ci-task-test.git
      SUB_PACKAGE: EmitterCI/emitter
  - put: emitter-image
    params:
      build: build-image/build
      tag: build-image/tag
      tag_as_latest: true
      cache: true
      cache_tag: latest

