name: gomod
on:
  push:
    branches:
      - 'develop'
    paths:
      - '.github/workflows/gomod.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    name: gomod
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.11'
        id: go
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CONCOURSE_METRIX_GH_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: gomod
        run: |
          go mod tidy
          go mod vendor

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
          else
            git add -A
            git config --global user.name "Log Store Bot"
            git config --global user.email "log-store@pivotal.io"
            git commit -m "Updating vendored dependencies"
            git push
          fi
